//***********************************************************************
//*                                                                     *
//*                  Copyright (c) 1985-2022, AMI.                      *
//*                                                                     *
//*      All rights reserved. Subject to AMI licensing agreement.       *
//*                                                                     *
//***********************************************************************
/**@file
 * This file contains the GPIO Handling functions
 */

#ifndef INTERRUPT_H_
#define INTERRUPT_H_

#include <stdlib.h>
#include <stddef.h>
#include <string.h>
/**
 * Interrupt Interface
 */
struct InterruptInterface {
	/**
	 * Function to initialize Timer Interrupt. 
	 *
	 * @param Interrupt Interface
	 *
	 * @return 0 
	 */
	int (*TimerInterrupt) ();

};

int InterruptInterface (struct InterruptInterface *Interrupt);

/**
 * Error codes that can be generated by a GPIO.
 */
enum {
	INTERRUPT_INVALID_ARGUMENT = 0x00		/**< Input parameter is null or not valid. */
};

#endif /* INTERRUPT_H_ */
