/*
 * Copyright (c) 2020 ASPEED
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_

#define ASPEED_CLK_GRP_0_OFFSET		(0)
#define ASPEED_CLK_GRP_1_OFFSET		(32)
#define ASPEED_CLK_GRP_2_OFFSET		(64)

#define ASPEED_CLK_GATE_MCLK		(ASPEED_CLK_GRP_0_OFFSET + 0)
#define ASPEED_CLK_GATE_USB_DEVICE	(ASPEED_CLK_GRP_0_OFFSET + 7)
#define ASPEED_CLK_GATE_YCLK		(ASPEED_CLK_GRP_0_OFFSET + 13)

#define ASPEED_CLK_GATE_LCLK		(ASPEED_CLK_GRP_1_OFFSET + 0)
#define ASPEED_CLK_GATE_ESPICLK		(ASPEED_CLK_GRP_1_OFFSET + 1)
#define ASPEED_CLK_GATE_REF1CLK		(ASPEED_CLK_GRP_1_OFFSET + 2)

#define ASPEED_CLK_GATE_LHCCLK		(ASPEED_CLK_GRP_1_OFFSET + 5)
#define ASPEED_CLK_GATE_RSACLK		(ASPEED_CLK_GRP_1_OFFSET + 6)

#define ASPEED_CLK_GATE_I3C0CLK		(ASPEED_CLK_GRP_1_OFFSET + 8)
#define ASPEED_CLK_GATE_I3C1CLK		(ASPEED_CLK_GRP_1_OFFSET + 9)
#define ASPEED_CLK_GATE_I3C2CLK		(ASPEED_CLK_GRP_1_OFFSET + 10)
#define ASPEED_CLK_GATE_I3C3CLK		(ASPEED_CLK_GRP_1_OFFSET + 11)

#define ASPEED_CLK_GATE_UART1CLK	(ASPEED_CLK_GRP_1_OFFSET + 16)
#define ASPEED_CLK_GATE_UART2CLK	(ASPEED_CLK_GRP_1_OFFSET + 17)
#define ASPEED_CLK_GATE_UART3CLK	(ASPEED_CLK_GRP_1_OFFSET + 18)
#define ASPEED_CLK_GATE_UART4CLK	(ASPEED_CLK_GRP_1_OFFSET + 19)
#define ASPEED_CLK_GATE_MACCLK		(ASPEED_CLK_GRP_1_OFFSET + 20)

#define ASPEED_CLK_GATE_UART6CLK	(ASPEED_CLK_GRP_1_OFFSET + 22)
#define ASPEED_CLK_GATE_UART7CLK	(ASPEED_CLK_GRP_1_OFFSET + 23)
#define ASPEED_CLK_GATE_UART8CLK	(ASPEED_CLK_GRP_1_OFFSET + 24)
#define ASPEED_CLK_GATE_UART9CLK	(ASPEED_CLK_GRP_1_OFFSET + 25)
#define ASPEED_CLK_GATE_UART10CLK	(ASPEED_CLK_GRP_1_OFFSET + 26)
#define ASPEED_CLK_GATE_UART11CLK	(ASPEED_CLK_GRP_1_OFFSET + 27)
#define ASPEED_CLK_GATE_UART12CLK	(ASPEED_CLK_GRP_1_OFFSET + 28)
#define ASPEED_CLK_GATE_UART13CLK	(ASPEED_CLK_GRP_1_OFFSET + 29)

#define ASPEED_CLK_PCLK			(ASPEED_CLK_GRP_2_OFFSET + 0)
#define ASPEED_CLK_HCLK			(ASPEED_CLK_GRP_2_OFFSET + 1)
#define ASPEED_CLK_UART5		(ASPEED_CLK_GRP_2_OFFSET + 2)
#define ASPEED_CLK_APB1			(ASPEED_CLK_GRP_2_OFFSET + 3)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_AST1030_H_ */
